---
  - name: Remove existing copy of dob-network on docker host ...
    command: bash -c "docker network rm dob-network 1 > /dev/null 2>&1 || true"
  - name: Add dob-network to docker host ...
    command: docker network create --driver bridge dob-network 
