# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dobdocker" do |dobdocker|
    dobdocker.vm.box = "shekeriev/centos-8-minimal"
    dobdocker.vm.hostname = "docker.dob.homework"
    dobdocker.vm.network "private_network", ip: "192.168.99.100"
    dobdocker.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    dobdocker.vm.synced_folder "website", "/home/vagrant/website"
    dobdocker.vm.provision "shell", path: "dobdocker.sh"
    dobdocker.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end
end
