# -*- mode: ruby -*-
# vi: set ft=ruby :

$add_hosts = <<SCRIPT
echo "192.168.98.100 dob-web dob-web" >> /etc/hosts
echo "192.168.98.101 dob-db dob-db" >> /etc/hosts
SCRIPT

$install_ansible = <<SCRIPT
sudo dnf install -y epel-release
sudo dnf install -y ansible
SCRIPT

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "ans" do |ans|
    ans.vm.box = "shekeriev/centos-8-minimal"
    ans.vm.hostname = "dob-ans"
    ans.vm.network "private_network", ip: "192.168.98.99"
    ans.vm.provision "shell", inline: $install_ansible
    ans.vm.provision "file", source: "./ans/inventory", destination: "/home/vagrant/ans/inventory"
    ans.vm.provision "file", source: "./ans/ansible.cfg", destination: "/home/vagrant/ans/ansible.cfg"
    ans.vm.provision "file", source: "./ans/playbook.yml", destination: "/home/vagrant/ans/playbook.yml"
    ans.vm.synced_folder "web", "/home/vagrant/web"
    ans.vm.synced_folder "db", "/home/vagrant/db"
  end

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-8-minimal"
    web.vm.hostname = "dob-web"
    web.vm.network "private_network", ip: "192.168.98.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provision "shell", inline: $add_hosts
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.hostname = "dob-db"
    db.vm.network "private_network", ip: "192.168.98.101"
    db.vm.provision "shell", inline: $add_hosts
  end
 
end