---
  - name: Install EPEL Repository
    dnf:
      name=epel-release
      state=present
  - name: Install NRPE
    dnf:
      name=nrpe,nagios-plugins-nrpe,nagios-plugins-all
      enablerepo=powertools
      state=present
  - name: Substitute nrpe.cfg
    copy:
      src=/tmp/files/nrpe.cfg
      dest=/etc/nagios/nrpe.cfg
  - name: Add nrpe to sudoers.d
    copy:
      src=/tmp/files/nrpe.sudo
      dest=/etc/sudoers.d/nrpe
  - name: Add nagios to sudoers.d
    copy:
      src=/tmp/files/nagios.sudo
      dest=/etc/sudoers.d/nagios
  - name: Adding user vagrant to docker group  
    user: name=vagrant
      groups=docker
      append=yes
  - name: Adding user nrpe to docker group  
    user: name=nrpe
      groups=docker
      append=yes
  - name: Adding user nagios to docker group  
    user: name=nagios
      groups=docker
      append=yes
  - name: Copy additional docker plugin
    copy:
      src=/tmp/files/check_docker_container.sh
      dest=/usr/lib64/nagios/plugins/check_docker_container.sh
  - name: Turn on execute permission for check_docker_container.sh
    file:
      path=/usr/lib64/nagios/plugins/check_docker_container.sh
      mode="a+x"
  - name: Enable and start NRPE
    service:
      name=nrpe
      state=started
      enabled=true
