# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="shekeriev/centos-8-minimal"
    web.vm.hostname = "web.dob.lab"
    web.vm.network "private_network", ip: "192.168.89.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.synced_folder "vagrant/web/", "/vagrant"
    web.vm.provision "shell", inline: <<EOS
echo "* Add hosts ..."
echo "192.168.89.100 web.dob.lab web" >> /etc/hosts
echo "192.168.89.101 db.dob.lab db" >> /etc/hosts

echo "* Install Software ..."
sudo dnf upgrade -y
sudo dnf install -y httpd php php-mysqlnd git

echo "* Start HTTP ..."
sudo systemctl enable httpd
sudo systemctl start httpd

echo "* Stop firewall ..."
sudo systemctl stop firewalld
sudo systemctl disable firewalld

echo "* Copy web site files to /var/www/html/ ..."
cp /vagrant/* /var/www/html

echo "* Allow HTTPD to make netork connections ..."
sudo setsebool -P httpd_can_network_connect=1
EOS
  end

  config.vm.define "db" do |db|
    db.vm.box="shekeriev/centos-8-minimal"
    db.vm.hostname = "dbo-db.dob.lab"
    db.vm.network "private_network", ip: "192.168.89.101"
    db.vm.synced_folder "vagrant/db/", "/vagrant"
    db.vm.provision "shell", inline: <<EOS
echo "* Add hosts ..."
echo "192.168.89.100 web.dob.lab web" >> /etc/hosts
echo "192.168.89.101 db.dob.lab db" >> /etc/hosts

echo "* Install Software ..."
sudo dnf upgrade -y
sudo dnf install -y mariadb mariadb-server

echo "* Start HTTP ..."
sudo systemctl enable mariadb
sudo systemctl start mariadb

echo "* Stop firewall ..."
sudo systemctl stop firewalld
sudo systemctl disable firewalld

echo "* Create and load the database ..."
mysql -u root < /vagrant/db_setup.sql
EOS
  end

end
 
