---
- hosts: docker
  become: true
  roles:
    - disable-selinux
    - add-hosts
    - firewall-http
    - firewall-nrpe
    - git
    - geerlingguy.java
    - geerlingguy.docker
    - nrpe
    - dob-network
